---
title: "tidytuesday_20190709"
author: "parmsam"
date: "7/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
theme_set(theme_light())

wwc_outcomes <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/wwc_outcomes.csv")
squads <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/squads.csv")
codes <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/codes.csv")
```

```{r}
wwc_outcomes <- dplyr::left_join(wwc_outcomes, codes, by = "team")

glimpse(wwc_outcomes)
glimpse(squads)

skim(wwc_outcomes)
skim(squads)

```

```{r}
wwc_outcomes %>% filter(str_detect(round,regex("Final"))) %>% 
  group_by(year, country) %>% count() %>% 
  group_by(country) %>% count() %>% ungroup() %>% mutate(country = fct_reorder(country,n)) %>%  
  ggplot(.,aes(x=country, y=n)) + geom_segment( aes(xend=country, y=0, yend=n) , size=1, color="skyblue" ) +
  geom_point( color="orange", size=4) + coord_flip() +
    labs(
    title="Appearances in Womens Soccer Finals (Semi, Quarter, or Grand Finals) 1991-2019",
    y="Number of Appearances",
    x="Country"
  )
ggsave("myplot1_20190709.png", width =10 , height=5)
```


```{r}
finals_winners  <- wwc_outcomes %>% filter(str_detect(round,regex("^Final")),win_status == "Won") %>%
  select(country,year, win_status)

wwc_outcomes %>% filter(str_detect(round,regex("Final"))) %>% 
  group_by(year, country) %>% count() %>% ungroup() %>%  group_by(year, country) %>% count()  %>% ungroup() %>%
  left_join(.,finals_winners,by=c("country","year")) %>% 
  mutate(year=as.factor(year)) %>% mutate(year=fct_reorder(year,-as.numeric(year))) %>%
  mutate(country=as.factor(country)) %>% mutate(country=fct_rev(country)) %>% 
  ggplot(.,aes(x=country, y=n, fill=year)) + geom_col() +coord_flip() + 
  labs(
    title="Appearances in Womens Soccer Finals (Semi, Quarter, or Grand Finals)  1991-2019",
    y="Number of Appearances",
    x="Country"
  ) + geom_text(aes(label=win_status), size = 3, position =position_stack(0.5))

ggsave("myplot2_20190709.png", width =10 , height=5)
```



